### PR TITLE
Add debian packaging

### PR DESCRIPTION
**Pull request by codenrhoden**
Signed-off-by: Travis Rhoden trhoden@redhat.com

### CODE REVIEW

**Comment by dmick** [comment]
Had some comments/suggestions @ktdreyer

**Comment by ktdreyer** [comment]
Looks good to me, and Jenkins builds it (http://jenkins.ceph.com/job/takora)

**Comment by ktdreyer** [comment]
The RPM ships Puppetfile, do we want to do that here?

**Comment by ktdreyer** [comment]
Whoops, I see we are doing that, in `takora.install`:

```
Puppetfile usr/share/ceph-puppet
```

Got it :)

**Comment by codenrhoden** [comment]
yeah, that was a change -- moved it from rules to takora.install for the simple things.  :)

**Pull request merged**
